# Problem 1

In [12]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
x = np.random.randint(0,10,5)
print(x)
# 3 - matris'in boyutunu öğrenin
print(x.shape)
# 4 - matris'i yeniden boyutlandırın
x.reshape(5,1)
print(x)
# 5 - matris'in boyut sayısını öğrenin
print(x.ndim)

[1 3 2 5 3]
(5,)
[1 3 2 5 3]
1


# Problem 2

In [17]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
y = np.arange(1,10,2)
print(y)
# 2 - Oluşturduğunuz matrisi parçalayın
a, b , c = np.split(y,[1,3])
print(a)
print(b)
print(c)
# 3 - Parçalanmış matrisleri birleştirin
print(np.concatenate([a,b,c]))

[1 3 5 7 9]
[1]
[3 5]
[7 9]
[1 3 5 7 9]


# Problem 3

In [23]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
z = np.arange(5,101,2)
rastgele = np.random.choice(z,size =10)
print(rastgele)
# 2 - matris'in özelliklerini inceleyin
print(rastgele.ndim)
print(rastgele.shape)
print(rastgele.size)
print(rastgele.dtype)

[65 81 67  5 93 79 81 51 61 81]
1
(10,)
10
int64
