# Problem 1 

In [14]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
x = np.random.rand(5)
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
x = np.sort(x)
print(x)

[0.30778514 0.33733556 0.40587091 0.78923124 0.90519603]


# Problem 2

In [30]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.

a = np.array([10,15,30,45,60])
print(a)
# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
b = np.arange(5, 15)
print(b)
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
c = np.arange(50,100,5)
print(c)
# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
y = np.zeros(10)
print(y)
# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
ones = np.ones(10)
print(ones)
# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
d = np.linspace(0,100,5)
print(d)
# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
e = np.random.randint(10,30,5)
print(e)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
z = np.linspace(-1,1,10)
print(z)
# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
matrix = np.random.randint(10, 51, size=(3, 5))
print(matrix)
# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
satir = np.sum(matrix, axis = 0)
sutun = np.sum(matrix, axis = 1)
print(satir, sutun)
# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
en_buyuk = np.max(matrix)
en_kucuk = np.min(matrix)
ort = np.mean(matrix)
print(en_buyuk, en_kucuk, ort)

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
flat_index = np.argmax(matrix)    #gemini
unraveled_index = np.unravel_index(flat_index, matrix.shape)  
print(unraveled_index)
# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
p = np.arange(10,20)
print(p[:3])

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(p[::-1])
# 15- Üretilen matrisin ilk satırını seçiniz.
print(matrix[0, :])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print("2.satır 3.sütundaki eleman:" , matrix[1, 2])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print("tüm satırlardaki ilk eleman arrayi" , matrix[:,0])

# 18- Üretilen matrisin her bir elemanının karesini alınız.
matrix = np.random.randint(10,51,size = (3,5))
print(matrix**2)
# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
matrix = np.random.randint(10,51,size = (3,5))
even_numbers = matrix[(matrix % 2 == 0) & (matrix > 0)]
print(even_numbers)


[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14]
[50 55 60 65 70 75 80 85 90 95]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[12 12 19 26 27]
[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]
[[28 26 49 35 15]
 [34 42 42 32 14]
 [15 18 12 33 38]]
[ 77  86 103 100  67] [153 164 116]
49 12 28.866666666666667
(np.int64(0), np.int64(2))
[10 11 12]
[19 18 17 16 15 14 13 12 11 10]
[28 26 49 35 15]
2.satır 3.sütundaki eleman: 42
tüm satırlardaki ilk eleman arrayi [28 34 15]
[[ 256 1521 2401  144 1296]
 [1024 1089 2401  529  256]
 [ 289 1521 2209  576  441]]
[22 26 24 20 18 32 14 14 26]


: 